# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_tblmain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class1',
            fields=[
                ('classnumber', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('fiscal_year', models.CharField(blank=True, db_column='fiscal year', max_length=50, null=True)),
                ('period', models.CharField(blank=True, max_length=50, null=True)),
                ('memo', models.TextField(blank=True, null=True)),
                ('prices', models.TextField(blank=True, null=True)),
                ('dates', models.TextField(blank=True, null=True)),
                ('age_grade', models.TextField(blank=True, db_column='age/grade', null=True)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('semester', models.CharField(blank=True, max_length=50, null=True)),
                ('time', models.CharField(blank=True, max_length=50, null=True)),
                ('instructor', models.CharField(blank=True, max_length=50, null=True)),
                ('maxsize', models.CharField(blank=True, max_length=50, null=True)),
                ('openstatus', models.CharField(blank=True, max_length=50, null=True)),
                ('active', models.IntegerField(blank=True, null=True)),
                ('enterdate', models.DateTimeField(blank=True, db_column='EnterDate', null=True)),
                ('room_location', models.CharField(blank=True, db_column='Room Location', max_length=50, null=True)),
                ('autofill', models.IntegerField(blank=True, null=True)),
                ('order', models.FloatField(blank=True, db_column='Order', null=True)),
                ('user', models.CharField(blank=True, db_column='User', max_length=50, null=True)),
            ],
            options={
                'db_table': 'class1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServersServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ip', models.CharField(max_length=39)),
                ('order', models.IntegerField()),
            ],
            options={
                'db_table': 'servers_server',
                'managed': False,
            },
        ),
    ]
