# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_class1_serversserver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mem',
            fields=[
                ('mem_id', models.IntegerField(primary_key=True, serialize=False)),
                ('mem_name', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=45)),
            ],
            options={
                'managed': False,
                'db_table': 'mem',
            },
        ),
    ]
