# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mem',
            fields=[
                ('mem_id', models.IntegerField(primary_key=True, serialize=False)),
                ('mem_name', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'mem',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='server',
            options={'managed': False},
        ),
    ]
