# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 23:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_auto_20170611_1418'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='server',
            table='servers_server',
        ),
    ]
