# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('registrationnumber', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, db_column='first name', max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, db_column='last Name', max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('emergencyphone', models.CharField(blank=True, max_length=50, null=True)),
                ('street_address', models.CharField(blank=True, db_column='street address', max_length=50, null=True)),
                ('citystatezip', models.CharField(blank=True, max_length=50, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('classnumber', models.IntegerField(blank=True, null=True)),
                ('attendance', models.CharField(blank=True, max_length=50, null=True)),
                ('memberid', models.IntegerField(blank=True, db_column='memberID', null=True)),
                ('receipt_field', models.CharField(blank=True, db_column='receipt #', max_length=50, null=True)),
                ('fee', models.FloatField(blank=True, db_column='Fee', null=True)),
                ('memo', models.TextField(blank=True, db_column='Memo', null=True)),
                ('applicationpath', models.TextField(blank=True, db_column='ApplicationPath', null=True)),
                ('applicationpath2', models.TextField(blank=True, db_column='ApplicationPath2', null=True)),
                ('date', models.DateTimeField(blank=True, db_column='Date', null=True)),
                ('user', models.CharField(blank=True, db_column='User', max_length=50, null=True)),
                ('cid1', models.IntegerField(blank=True, db_column='CID1', null=True)),
                ('ca', models.CharField(blank=True, db_column='Ca', max_length=50, null=True)),
                ('cid2', models.IntegerField(blank=True, db_column='CID2', null=True)),
                ('cb', models.CharField(blank=True, db_column='Cb', max_length=50, null=True)),
                ('cid3', models.IntegerField(blank=True, db_column='CID3', null=True)),
                ('cc', models.CharField(blank=True, db_column='Cc', max_length=50, null=True)),
                ('cid4', models.IntegerField(blank=True, db_column='CID4', null=True)),
                ('cd', models.CharField(blank=True, db_column='Cd', max_length=50, null=True)),
                ('sex', models.CharField(blank=True, max_length=50, null=True)),
                ('zip', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('dob', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'registration',
                'managed': False,
            },
        ),
    ]
