# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class1',
            fields=[
                ('classnumber', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('fiscal_year', models.CharField(blank=True, db_column='fiscal year', max_length=50, null=True)),
                ('period', models.CharField(blank=True, max_length=50, null=True)),
                ('memo', models.TextField(blank=True, null=True)),
                ('prices', models.TextField(blank=True, null=True)),
                ('dates', models.TextField(blank=True, null=True)),
                ('age_grade', models.TextField(blank=True, db_column='age/grade', null=True)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('semester', models.CharField(blank=True, max_length=50, null=True)),
                ('time', models.CharField(blank=True, max_length=50, null=True)),
                ('instructor', models.CharField(blank=True, max_length=50, null=True)),
                ('maxsize', models.CharField(blank=True, max_length=50, null=True)),
                ('openstatus', models.CharField(blank=True, max_length=50, null=True)),
                ('active', models.IntegerField(blank=True, null=True)),
                ('enterdate', models.DateTimeField(blank=True, db_column='EnterDate', null=True)),
                ('room_location', models.CharField(blank=True, db_column='Room Location', max_length=50, null=True)),
                ('autofill', models.IntegerField(blank=True, null=True)),
                ('order', models.FloatField(blank=True, db_column='Order', null=True)),
                ('user', models.CharField(blank=True, db_column='User', max_length=50, null=True)),
            ],
            options={
                'db_table': 'class1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblmain',
            fields=[
                ('memberid', models.AutoField(db_column='memberID', primary_key=True, serialize=False)),
                ('mem_id', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, db_column='Date', null=True)),
                ('firstname', models.CharField(blank=True, db_column='FirstName', max_length=30, null=True)),
                ('lastname', models.CharField(blank=True, db_column='LastName', max_length=50, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=255, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=50, null=True)),
                ('state', models.CharField(blank=True, db_column='State', max_length=20, null=True)),
                ('postalcode', models.CharField(blank=True, db_column='PostalCode', max_length=20, null=True)),
                ('phonenumber', models.CharField(blank=True, db_column='PhoneNumber', max_length=30, null=True)),
                ('cellnumber', models.CharField(blank=True, db_column='CellNumber', max_length=50, null=True)),
                ('emailaddress', models.CharField(blank=True, db_column='EmailAddress', max_length=50, null=True)),
                ('sex', models.CharField(blank=True, db_column='Sex', max_length=1, null=True)),
                ('dob', models.DateTimeField(blank=True, db_column='DOB', null=True)),
                ('school', models.CharField(blank=True, db_column='School', max_length=20, null=True)),
                ('grade', models.CharField(blank=True, db_column='Grade', max_length=50, null=True)),
                ('class_field', models.CharField(blank=True, db_column='Class', max_length=50, null=True)),
                ('age', models.IntegerField(blank=True, db_column='Age', null=True)),
                ('notes', models.TextField(blank=True, db_column='Notes', null=True)),
                ('medical', models.TextField(blank=True, db_column='Medical', null=True)),
                ('mbusiness_phone', models.CharField(blank=True, db_column='mBusiness_Phone', max_length=30, null=True)),
                ('mcell_phone', models.CharField(blank=True, db_column='mCell_Phone', max_length=30, null=True)),
                ('fathers_name', models.CharField(blank=True, db_column='Fathers_Name', max_length=30, null=True)),
                ('fbusiness_phone', models.CharField(blank=True, db_column='fBusiness_Phone', max_length=30, null=True)),
                ('membership_status', models.CharField(blank=True, db_column='Membership_status', max_length=15, null=True)),
                ('regdate', models.DateTimeField(blank=True, db_column='RegDate', null=True)),
                ('expdate', models.DateTimeField(blank=True, db_column='ExpDate', null=True)),
                ('user', models.CharField(blank=True, db_column='User', max_length=50, null=True)),
                ('combo', models.CharField(blank=True, db_column='Combo', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tblMain',
                'managed': False,
            },
        ),
    ]
